[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
futures = "0.3"
image = "0.24"
scrap = "0.5"
enigo = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rsa = "0.9"
aes = "0.8"
